export const IMAGES = {
  logo: "/assets/icons/logo.svg",
  microsoft: "/assets/icons/microsoft.svg",
  notificationIcon: "/assets/icons/notification-icon.svg",
  commentIcon: "/assets/icons/comment.svg",
  exportIcon: "/assets/icons/export.svg",
  copyIcon: "/assets/icons/copy-icon.svg",
  addFlagIcon: "/assets/icons/add-flag-icon.svg",
  avatarImage: "/assets/images/avatar.jpg",
  pdfIcon: "/assets/icons/pdf-icon.svg",
  xlsIcon: "/assets/icons/xls-icon.svg",
  commentPlusIcon: "/assets/icons/comment-plus-icon.svg",
  commentPlusGreenIcon: "/assets/icons/comment-plus-green-icon.svg",
  sourceFolderIcon: "/assets/icons/source-folder-icon.svg",
  sendIcon: "/assets/icons/send.svg",
  replyIcon: "/assets/icons/reply.svg",
  flagIcon: "/assets/icons/flag-icon.svg",
  checkPrimaryIcon: "/assets/icons/check-primary-icon.svg",
  projectDetailBg: "/assets/images/project-detail-bg.svg",
};
